### PR TITLE
Add Recompute button to reports

### LINKED ISSUE #224: add recompute report button somewhere
perhaps at the top of the report page? Should probably also catch errors when trying to render the report here https://github.com/SolarArbiter/solarforecastarbiter_dashboard/blob/7f538d90331e27bc145a623aebef580738056462/sfa_dash/blueprints/reports.py#L163

### PR DESCRIPTION
**Pull request by lboeman**
closes #224 
Adds a recompute button to reports just below the report's title. Positioning seems a little bit awkward but I'm not sure there's a better place for it.
Screenshot from 2020-05-14 15-44-25

### CODE REVIEW

**Comment by alorenzo175** [comment]
as for the location, I think on the the right edge aligned with the title would be better maybe? but not if the title is long?idk, it's ok where it is

**Comment by lboeman** [comment]
> as for the location, I think on the the right edge aligned with the title would be better maybe? but not if the title is long?idk, it's ok where it is

Yeah, just trying it out, it causes some weird wrapping for the header text. Where it is will work for now. Thanks for reviewing.

**Comment by wholmgren** [comment]
I'm good with the simple below the title positioning. 

Is the button only visible if you actually have the ability to recreate the report (rather than just view it)?

**Comment by lboeman** [comment]
> I'm good with the simple below the title positioning.
> 
> Is the button only visible if you actually have the ability to recreate the report (rather than just view it)?

It only shows up if you have "Update" permissions on the report. However, you need access to all of the objects referenced by the report for it to recompute successfullly.

**Comment by lboeman** [comment]
Clear to merge this?

**Comment by wholmgren** [comment]
Yes

**Pull request merged**
